# docker-compose.yml
version: '3'

services:
  sftp-server:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ./upload:/home/foo/upload
    command: foo:pass:1001

volumes:
  sftp-volume: